import { soundList } from './sounds.js';
const audioCtx=new(window.AudioContext||window.webkitAudioContext)(),catalog=document.querySelector('#catalog'),filters=document.querySelector('#filters'),search=document.querySelector('#search'),count=document.querySelector('#resultCount'),empty=document.querySelector('#empty'),volume=document.querySelector('#volume'),volumeValue=document.querySelector('#volumeValue'),toast=document.querySelector('#toast');
let category='すべて',activeCard=null,toastTimer;const favorites=new Set(JSON.parse(localStorage.getItem('sound-recipe-favorites')||'[]'));
const categories=['すべて',...new Set(soundList.map(s=>s.category))];filters.innerHTML=categories.map((c,i)=>`<button class="filter${i?'':' active'}" type="button" role="tab" aria-selected="${!i}" data-category="${c}">${c}</button>`).join('');
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),1900)}
function visible(){const word=search.value.trim().toLowerCase();return soundList.filter(s=>(category==='すべて'||s.category===category)&&(!word||`${s.name} ${s.desc} ${s.category} ${s.use}`.toLowerCase().includes(word)))}
function render(){const list=visible();count.textContent=`${list.length} / ${soundList.length} recipes`;empty.classList.toggle('hidden',!!list.length);catalog.innerHTML=list.map(s=>{const bars=Array.from({length:22},(_,i)=>`<i style="--h:${16+(i*17+s.id.length*7)%28}px"></i>`).join('');return `<article class="card" data-id="${s.id}" style="--card-color:${s.color}"><div class="card-top"><span class="tag">#${s.id} · ${s.category} / ${s.use}</span><button class="favorite${favorites.has(s.id)?' on':''}" data-favorite="${s.id}" aria-label="${s.name}をお気に入りに登録">★</button></div><h3>${s.name}</h3><p>${s.desc}</p><div class="sound-meta">使う場面：${s.use}　｜　${s.duration.toFixed(2)}秒</div><div class="wave" aria-hidden="true">${bars}</div><div class="card-actions"><button class="btn btn-play" data-play="${s.id}">▶ 試聴する</button><button class="btn btn-copy" data-copy="${s.id}">コード</button></div></article>`}).join('')}
async function play(sound){if(audioCtx.state==='suspended')await audioCtx.resume();if(activeCard)activeCard.classList.remove('playing');activeCard=document.querySelector(`[data-id="${sound.id}"]`);if(activeCard)activeCard.classList.add('playing');const duration=sound.play(audioCtx,Number(volume.value)/100),button=activeCard?.querySelector('.btn-play');if(button)button.textContent='♪ 再生中';setTimeout(()=>{if(activeCard)activeCard.classList.remove('playing');if(button)button.textContent='▶ 試聴する';activeCard=null},duration*1000+80)}
catalog.addEventListener('click',async e=>{const playButton=e.target.closest('[data-play]'),copyButton=e.target.closest('[data-copy]'),fav=e.target.closest('[data-favorite]');if(playButton)play(soundList.find(s=>s.id===playButton.dataset.play));if(copyButton){const s=soundList.find(x=>x.id===copyButton.dataset.copy);await navigator.clipboard.writeText(s.code);copyButton.textContent='✓ コピー済';copyButton.classList.add('copied');showToast(`${s.name}のコードをコピーしました`);setTimeout(()=>{copyButton.textContent='コード';copyButton.classList.remove('copied')},1800)}if(fav){const id=fav.dataset.favorite;favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem('sound-recipe-favorites',JSON.stringify([...favorites]));render();showToast(favorites.has(id)?'お気に入りに追加しました':'お気に入りから外しました')}});
filters.addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;category=b.dataset.category;filters.querySelectorAll('.filter').forEach(x=>{const on=x===b;x.classList.toggle('active',on);x.setAttribute('aria-selected',on)});render()});search.addEventListener('input',render);volume.addEventListener('input',()=>{volumeValue.value=`${volume.value}%`;volumeValue.textContent=`${volume.value}%`});document.querySelector('#playAll').addEventListener('click',async()=>{for(const s of visible()){await play(s);await new Promise(r=>setTimeout(r,s.duration*1000+180))}});render();
